# Generated by Django 2.1.7 on 2019-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190331_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
