# Generated by Django 2.1.7 on 2019-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_navlinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='链接名')),
                ('url', models.URLField(verbose_name='外链地址')),
            ],
            options={
                'verbose_name': '导航外链',
                'verbose_name_plural': '导航外链',
            },
        ),
    ]
